
export interface Station {
  id: string;
  name: string;
  code: string;
  lines: ('Blue' | 'Green' | 'Purple' | 'Orange' | 'Yellow')[];
  gates: number;
  facilities: string[];
  firstTrain: string;
  lastTrain:string;
  platformInfo: string;
}

export interface Fare {
  from: string;
  to: string;
  fare: number;
}

export interface Line {
  name: 'Blue' | 'Green' | 'Purple' | 'Orange' | 'Yellow';
  stations: string[];
}

export const stations: Station[] = [
    // Blue Line (North-South)
    { id: 'dakshineswar', name: 'Dakshineswar', code: 'DKS', lines: ['Blue'], gates: 4, facilities: ["Elevator", "Escalator", "Toilets"], firstTrain: "06:45", lastTrain: "21:30", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Terminating" },
    { id: 'baranagar', name: 'Baranagar', code: 'BRN', lines: ['Blue'], gates: 2, facilities: ["Elevator", "Toilets"], firstTrain: "06:48", lastTrain: "21:33", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dakshineswar" },
    { id: 'noapara', name: 'Noapara', code: 'NOA', lines: ['Blue', 'Yellow'], gates: 3, facilities: ["Elevator", "Escalator", "Parking", "Interchange"], firstTrain: "06:50", lastTrain: "21:35", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dakshineswar" },
    { id: 'dum-dum', name: 'Dum Dum', code: 'DDM', lines: ['Blue'], gates: 5, facilities: ["Elevator", "Escalator", "Food Court", "Parking", "Toilets"], firstTrain: "06:45", lastTrain: "22:00", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dakshineswar | Platform 3 & 4: Indian Railways" },
    { id: 'belgachia', name: 'Belgachia', code: 'BGA', lines: ['Blue'], gates: 2, facilities: ["Escalator", "Toilets"], firstTrain: "06:48", lastTrain: "21:57", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'shyambazar', name: 'Shyambazar', code: 'SMB', lines: ['Blue'], gates: 3, facilities: ["Elevator"], firstTrain: "06:51", lastTrain: "21:54", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'shobhabazar-sutanuti', name: 'Shobhabazar Sutanuti', code: 'SST', lines: ['Blue'], gates: 2, facilities: [], firstTrain: "06:53", lastTrain: "21:52", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'girish-park', name: 'Girish Park', code: 'GIR', lines: ['Blue'], gates: 2, facilities: [], firstTrain: "06:55", lastTrain: "21:50", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'mahatma-gandhi-road', name: 'Mahatma Gandhi Road', code: 'MGR', lines: ['Blue'], gates: 4, facilities: ["Escalator"], firstTrain: "06:57", lastTrain: "21:48", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'central', name: 'Central', code: 'CEN', lines: ['Blue'], gates: 4, facilities: ["Elevator", "Escalator"], firstTrain: "06:59", lastTrain: "21:46", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'chandni-chowk', name: 'Chandni Chowk', code: 'CHC', lines: ['Blue'], gates: 4, facilities: ["Elevator", "Escalator"], firstTrain: "07:01", lastTrain: "21:44", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'esplanade', name: 'Esplanade', code: 'ESP', lines: ['Blue', 'Green'], gates: 6, facilities: ["Elevator", "Escalator", "Interchange", "Toilets"], firstTrain: "07:00", lastTrain: "21:45", platformInfo: "Blue Line: P1 Kavi Subhash, P2 Dum Dum | Green Line: P1 Howrah Maidan, P2 Sealdah" },
    { id: 'park-street', name: 'Park Street', code: 'PST', lines: ['Blue'], gates: 4, facilities: ["Elevator", "Escalator"], firstTrain: "07:03", lastTrain: "21:42", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'maidan', name: 'Maidan', code: 'MDN', lines: ['Blue'], gates: 2, facilities: [], firstTrain: "07:05", lastTrain: "21:40", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'rabindra-sadan', name: 'Rabindra Sadan', code: 'RSD', lines: ['Blue'], gates: 2, facilities: ["Escalator"], firstTrain: "07:07", lastTrain: "21:38", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'netaji-bhavan', name: 'Netaji Bhavan', code: 'NBH', lines: ['Blue'], gates: 2, facilities: ["Escalator"], firstTrain: "07:09", lastTrain: "21:36", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'jatindas-park', name: 'Jatindas Park', code: 'JDP', lines: ['Blue'], gates: 3, facilities: [], firstTrain: "07:11", lastTrain: "21:34", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'kalighat', name: 'Kalighat', code: 'KGT', lines: ['Blue'], gates: 4, facilities: ["Elevator", "Escalator"], firstTrain: "07:13", lastTrain: "21:32", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'rabindra-sarobar', name: 'Rabindra Sarobar', code: 'RBS', lines: ['Blue'], gates: 3, facilities: ["Parking"], firstTrain: "07:15", lastTrain: "21:30", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'mahanayak-uttam-kumar', name: 'Mahanayak Uttam Kumar', code: 'MUK', lines: ['Blue'], gates: 4, facilities: ["Elevator", "Escalator", "Parking"], firstTrain: "06:45", lastTrain: "21:55", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'netaji', name: 'Netaji', code: 'NTJ', lines: ['Blue'], gates: 2, facilities: [], firstTrain: "06:51", lastTrain: "21:51", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'masterda-surya-sen', name: 'Masterda Surya Sen', code: 'MSS', lines: ['Blue'], gates: 2, facilities: [], firstTrain: "06:54", lastTrain: "21:48", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'gitanjali', name: 'Gitanjali', code: 'GTN', lines: ['Blue'], gates: 2, facilities: [], firstTrain: "06:56", lastTrain: "21:46", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'kavi-nazrul', name: 'Kavi Nazrul', code: 'KZN', lines: ['Blue'], gates: 3, facilities: ["Elevator", "Escalator"], firstTrain: "06:58", lastTrain: "21:44", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'shahid-khudiram', name: 'Shahid Khudiram', code: 'SKD', lines: ['Blue'], gates: 2, facilities: [], firstTrain: "07:01", lastTrain: "21:41", platformInfo: "Platform 1: Kavi Subhash | Platform 2: Dum Dum" },
    { id: 'kavi-subhash', name: 'Kavi Subhash', code: 'KVS', lines: ['Blue', 'Orange'], gates: 4, facilities: ["Elevator", "Escalator", "Parking", "Toilets", "Interchange"], firstTrain: "06:45", lastTrain: "21:45", platformInfo: "Blue Line: P1 Terminating, P2 Dakshineswar | Orange Line: Interchange" },

    // Green Line (East-West)
    { id: 'salt-lake-sector-v', name: 'Salt Lake Sector V', code: 'SLV', lines: ['Green'], gates: 3, facilities: ["Elevator", "Toilets", "Wifi"], firstTrain: "06:55", lastTrain: "22:00", platformInfo: "Platform 1: Howrah Maidan | Platform 2: Terminating" },
    { id: 'karunamoyee', name: 'Karunamoyee', code: 'KRM', lines: ['Green'], gates: 2, facilities: ["Escalator", "Toilets"], firstTrain: "06:58", lastTrain: "21:57", platformInfo: "Platform 1: Howrah Maidan | Platform 2: Salt Lake Sector V" },
    { id: 'central-park', name: 'Central Park', code: 'CPK', lines: ['Green'], gates: 2, facilities: ["Parking"], firstTrain: "07:00", lastTrain: "21:55", platformInfo: "Platform 1: Howrah Maidan | Platform 2: Salt Lake Sector V" },
    { id: 'city-center', name: 'City Center', code: 'CIT', lines: ['Green'], gates: 2, facilities: [], firstTrain: "07:02", lastTrain: "21:53", platformInfo: "Platform 1: Howrah Maidan | Platform 2: Salt Lake Sector V" },
    { id: 'bengal-chemical', name: 'Bengal Chemical', code: 'BNC', lines: ['Green'], gates: 2, facilities: [], firstTrain: "07:04", lastTrain: "21:51", platformInfo: "Platform 1: Howrah Maidan | Platform 2: Salt Lake Sector V" },
    { id: 'salt-lake-stadium', name: 'Salt Lake Stadium', code: 'SLS', lines: ['Green'], gates: 3, facilities: ["Elevator", "Escalator"], firstTrain: "07:07", lastTrain: "21:48", platformInfo: "Platform 1: Howrah Maidan | Platform 2: Salt Lake Sector V" },
    { id: 'phoolbagan', name: 'Phoolbagan', code: 'PHB', lines: ['Green'], gates: 2, facilities: ["Elevator", "Escalator"], firstTrain: "07:10", lastTrain: "21:45", platformInfo: "Platform 1: Howrah Maidan | Platform 2: Salt Lake Sector V" },
    { id: 'sealdah', name: 'Sealdah', code: 'SDH', lines: ['Green'], gates: 4, facilities: ["Elevator", "Escalator", "Interchange", "Toilets"], firstTrain: "07:00", lastTrain: "21:40", platformInfo: "Platform 1: Howrah Maidan | Platform 2: Salt Lake Sector V | Indian Railways Interchange" },
    { id: 'mahakaran', name: 'Mahakaran', code: 'MHK', lines: ['Green'], gates: 4, facilities: ["Elevator", "Escalator", "Toilets"], firstTrain: "07:00", lastTrain: "21:40", platformInfo: "Platform 1: Howrah Maidan | Platform 2: Salt Lake Sector V" },
    { id: 'howrah', name: 'Howrah', code: 'HWH', lines: ['Green'], gates: 5, facilities: ["Elevator", "Escalator", "Toilets"], firstTrain: "07:00", lastTrain: "21:30", platformInfo: "Platform 1: Salt Lake Sector V | Platform 2: Terminating" },
    { id: 'howrah-maidan', name: 'Howrah Maidan', code: 'HWM', lines: ['Green'], gates: 3, facilities: ["Elevator", "Escalator"], firstTrain: "07:00", lastTrain: "21:30", platformInfo: "Platform 1: Salt Lake Sector V | Platform 2: Terminating" },

    // Purple Line (Joka-Esplanade)
    { id: 'joka', name: 'Joka', code: 'JOK', lines: ['Purple'], gates: 2, facilities: ["Parking"], firstTrain: "08:55", lastTrain: "16:00", platformInfo: "Platform 1: Majherhat | Platform 2: Terminating" },
    { id: 'thakurpukur-cancer-hospital', name: 'Thakurpukur Cancer Hospital', code: 'TCP', lines: ['Purple'], gates: 2, facilities: [], firstTrain: "09:00", lastTrain: "16:05", platformInfo: "Platform 1: Majherhat | Platform 2: Joka" },
    { id: 'sakherbazar', name: 'Sakherbazar', code: 'SKB', lines: ['Purple'], gates: 2, facilities: [], firstTrain: "09:03", lastTrain: "16:08", platformInfo: "Platform 1: Majherhat | Platform 2: Joka" },
    { id: 'behala-chowrasta', name: 'Behala Chowrasta', code: 'BHC', lines: ['Purple'], gates: 2, facilities: ["Escalator"], firstTrain: "09:05", lastTrain: "16:10", platformInfo: "Platform 1: Majherhat | Platform 2: Joka" },
    { id: 'behala-bazar', name: 'Behala Bazar', code: 'BHB', lines: ['Purple'], gates: 2, facilities: [], firstTrain: "09:08", lastTrain: "16:13", platformInfo: "Platform 1: Majherhat | Platform 2: Joka" },
    { id: 'taratala', name: 'Taratala', code: 'TAR', lines: ['Purple'], gates: 2, facilities: ["Elevator"], firstTrain: "09:12", lastTrain: "16:17", platformInfo: "Platform 1: Majherhat | Platform 2: Joka" },
    { id: 'majherhat', name: 'Majherhat', code: 'MAJ', lines: ['Purple'], gates: 3, facilities: ["Elevator", "Escalator", "Interchange"], firstTrain: "09:15", lastTrain: "16:20", platformInfo: "Platform 1: Terminating | Platform 2: Joka | Indian Railways Interchange" },

    // Orange Line (Kavi Subhash-Jai Hind)
    { id: 'satyajit-ray', name: 'Satyajit Ray', code: 'SJR', lines: ['Orange'], gates: 2, facilities: [], firstTrain: "09:03", lastTrain: "16:43", platformInfo: "Platform 1: Jai Hind | Platform 2: Kavi Subhash" },
    { id: 'jyotirindra-nandi', name: 'Jyotirindra Nandi', code: 'JYN', lines: ['Orange'], gates: 2, facilities: [], firstTrain: "09:05", lastTrain: "16:45", platformInfo: "Platform 1: Jai Hind | Platform 2: Kavi Subhash" },
    { id: 'kavi-sukanta', name: 'Kavi Sukanta', code: 'KSK', lines: ['Orange'], gates: 2, facilities: [], firstTrain: "09:08", lastTrain: "16:48", platformInfo: "Platform 1: Jai Hind | Platform 2: Kavi Subhash" },
    { id: 'hemanta-mukhopadhyay', name: 'Hemanta Mukhopadhyay', code: 'HMK', lines: ['Orange'], gates: 2, facilities: [], firstTrain: "09:10", lastTrain: "16:50", platformInfo: "Platform 1: Jai Hind | Platform 2: Kavi Subhash" },
    { id: 'vip-bazar', name: 'VIP Bazar', code: 'VIP', lines: ['Orange'], gates: 2, facilities: [], firstTrain: "09:13", lastTrain: "16:53", platformInfo: "Platform 1: Jai Hind | Platform 2: Kavi Subhash" },
    { id: 'ritwik-ghatak', name: 'Ritwik Ghatak', code: 'RTG', lines: ['Orange'], gates: 2, facilities: [], firstTrain: "09:15", lastTrain: "16:55", platformInfo: "Platform 1: Jai Hind | Platform 2: Kavi Subhash" },
    { id: 'barun-sengupta', name: 'Barun Sengupta', code: 'BSG', lines: ['Orange'], gates: 2, facilities: [], firstTrain: "09:18", lastTrain: "16:58", platformInfo: "Platform 1: Jai Hind | Platform 2: Kavi Subhash" },
    { id: 'beleghata', name: 'Beleghata', code: 'BLG', lines: ['Orange'], gates: 2, facilities: [], firstTrain: "09:21", lastTrain: "17:01", platformInfo: "Platform 1: Jai Hind | Platform 2: Kavi Subhash" },
    { id: 'subhas-sarobar', name: 'Subhas Sarobar', code: 'SSR', lines: ['Orange'], gates: 2, facilities: [], firstTrain: "09:24", lastTrain: "17:04", platformInfo: "Platform 1: Jai Hind | Platform 2: Kavi Subhash" },

    // Yellow Line
    { id: 'dumdum-cantonment', name: 'Dumdum Cantonment', code: 'DDC', lines: ['Yellow'], gates: 2, facilities: ["Toilets"], firstTrain: "07:00", lastTrain: "21:00", platformInfo: "Platform 1: Jai Hind | Platform 2: Noapara" },
    { id: 'jessore-road', name: 'Jessore Road', code: 'JSR', lines: ['Yellow'], gates: 2, facilities: ["Toilets"], firstTrain: "07:05", lastTrain: "20:55", platformInfo: "Platform 1: Jai Hind | Platform 2: Noapara" },
    { id: 'jai-hind', name: 'Jai Hind (Airport)', code: 'JHD', lines: ['Yellow'], gates: 3, facilities: ["Elevator", "Escalator", "Interchange with Airport"], firstTrain: "07:10", lastTrain: "20:50", platformInfo: "Platform 1: Terminating | Platform 2: Noapara" }
];

export const lines: Line[] = [
  {
    name: 'Blue',
    stations: [
      'dakshineswar', 'baranagar', 'noapara', 'dum-dum', 'belgachia', 'shyambazar',
      'shobhabazar-sutanuti', 'girish-park', 'mahatma-gandhi-road', 'central',
      'chandni-chowk', 'esplanade', 'park-street', 'maidan', 'rabindra-sadan', 'netaji-bhavan', 'jatindas-park', 'kalighat', 'rabindra-sarobar', 'mahanayak-uttam-kumar',
      'netaji', 'masterda-surya-sen', 'gitanjali', 'kavi-nazrul',
      'shahid-khudiram', 'kavi-subhash'
    ],
  },
  {
    name: 'Green',
    stations: [
      'howrah-maidan', 'howrah', 'mahakaran', 'esplanade', 'sealdah', 'phoolbagan', 'salt-lake-stadium',
      'bengal-chemical', 'city-center', 'central-park', 'karunamoyee', 'salt-lake-sector-v'
    ],
  },
  {
      name: 'Purple',
      stations: [
          'joka', 'thakurpukur-cancer-hospital', 'sakherbazar', 'behala-chowrasta', 'behala-bazar', 'taratala', 'majherhat'
      ]
  },
  {
      name: 'Orange',
      stations: [
        'kavi-subhash', 'satyajit-ray', 'jyotirindra-nandi', 'kavi-sukanta',
        'hemanta-mukhopadhyay', 'vip-bazar', 'ritwik-ghatak', 'barun-sengupta', 'beleghata', 'subhas-sarobar'
      ]
  },
  {
      name: 'Yellow',
      stations: [
          'noapara', 'dumdum-cantonment', 'jessore-road', 'jai-hind'
      ]
  }
];

export const fares: Fare[] = [
  // Blue Line Fares
  { from: 'dakshineswar', to: 'baranagar', fare: 10 },
  { from: 'dakshineswar', to: 'noapara', fare: 15 },
  { from: 'dakshineswar', to: 'dum-dum', fare: 15 },
  { from: 'dakshineswar', to: 'belgachia', fare: 20 },
  { from: 'dakshineswar', to: 'shyambazar', fare: 20 },
  { from: 'dakshineswar', to: 'shobhabazar-sutanuti', fare: 20 },
  { from: 'dakshineswar', to: 'girish-park', fare: 20 },
  { from: 'dakshineswar', to: 'mahatma-gandhi-road', fare: 25 },
  { from: 'dakshineswar', to: 'central', fare: 25 },
  { from: 'dakshineswar', to: 'chandni-chowk', fare: 25 },
  { from: 'dakshineswar', to: 'esplanade', fare: 25 },
  { from: 'dakshineswar', to: 'park-street', fare: 25 },
  { from: 'dakshineswar', to: 'maidan', fare: 25 },
  { from: 'dakshineswar', to: 'rabindra-sadan', fare: 25 },
  { from: 'dakshineswar', to: 'netaji-bhavan', fare: 30 },
  { from: 'dakshineswar', to: 'jatindas-park', fare: 30 },
  { from: 'dakshineswar', to: 'kalighat', fare: 30 },
  { from: 'dakshineswar', to: 'rabindra-sarobar', fare: 30 },
  { from: 'dakshineswar', to: 'mahanayak-uttam-kumar', fare: 30 },
  { from: 'dakshineswar', to: 'netaji', fare: 30 },
  { from: 'dakshineswar', to: 'masterda-surya-sen', fare: 30 },
  { from: 'dakshineswar', to: 'gitanjali', fare: 30 },
  { from: 'dakshineswar', to: 'kavi-nazrul', fare: 30 },
  { from: 'dakshineswar', to: 'shahid-khudiram', fare: 30 },
  { from: 'dakshineswar', to: 'kavi-subhash', fare: 30 },
  { from: 'dum-dum', to: 'kavi-subhash', fare: 25 },
  { from: 'dum-dum', to: 'mahanayak-uttam-kumar', fare: 20 },
  { from: 'esplanade', to: 'kavi-subhash', fare: 20 },
  { from: 'esplanade', to: 'mahanayak-uttam-kumar', fare: 15 },
  { from: 'esplanade', to: 'park-street', fare: 5 },
  
  // Base Fares
  { from: 'howrah-maidan', to: 'howrah', fare: 5 },
  { from: 'howrah-maidan', to: 'esplanade', fare: 10 },
  { from: 'howrah-maidan', to: 'sealdah', fare: 20 },
  { from: 'howrah-maidan', to: 'salt-lake-sector-v', fare: 30 },
  { from: 'howrah', to: 'mahakaran', fare: 10 },
  { from: 'dakshineswar', to: 'karunamoyee', fare: 50 },
  { from: 'dakshineswar', to: 'central-park', fare: 40 },
  { from: 'dakshineswar', to: 'city-center', fare: 40 },
  { from: 'dakshineswar', to: 'salt-lake-sector-v', fare: 50 },
  { from: 'dakshineswar', to: 'bengal-chemical', fare: 40 },
  { from: 'dakshineswar', to: 'salt-lake-stadium', fare: 40 },
  { from: 'baranagar', to: 'karunamoyee', fare: 50 },
  { from: 'baranagar', to: 'central-park', fare: 40 },
  { from: 'baranagar', to: 'city-center', fare: 40 },
  { from: 'baranagar', to: 'salt-lake-sector-v', fare: 50 },
  { from: 'baranagar', to: 'bengal-chemical', fare: 40 },
  { from: 'baranagar', to: 'salt-lake-stadium', fare: 40 },
  { from: 'noapara', to: 'karunamoyee', fare: 50 },
  { from: 'noapara', to: 'central-park', fare: 40 },
  { from: 'noapara', to: 'city-center', fare: 40 },
  { from: 'noapara', to: 'salt-lake-sector-v', fare: 50 },
  { from: 'noapara', to: 'bengal-chemical', fare: 40 },
  { from: 'noapara', to: 'salt-lake-stadium', fare: 40 },
  { from: 'jai-hind', to: 'jessore-road', fare: 5 },
  { from: 'jai-hind', to: 'dumdum-cantonment', fare: 10 },
  { from: 'jai-hind', to: 'noapara', fare: 20 },
  { from: 'kavi-subhash', to: 'hemanta-mukhopadhyay', fare: 20 },
  { from: 'kavi-subhash', to: 'beleghata', fare: 20 },
  
  // From Jai Hind (Airport)
  { from: 'jai-hind', to: 'shyambazar', fare: 35 },
  { from: 'jai-hind', to: 'central', fare: 35 },
  { from: 'jai-hind', to: 'girish-park', fare: 35 },
  { from: 'jai-hind', to: 'esplanade', fare: 40 },
  { from: 'jai-hind', to: 'park-street', fare: 40 },
  { from: 'jai-hind', to: 'rabindra-sarobar', fare: 40 },
  { from: 'jai-hind', to: 'netaji', fare: 45 },
  { from: 'jai-hind', to: 'kavi-subhash', fare: 45 },
  { from: 'jai-hind', to: 'phoolbagan', fare: 50 },
  { from: 'jai-hind', to: 'sealdah', fare: 50 },
  { from: 'jai-hind', to: 'howrah', fare: 50 },
  { from: 'jai-hind', to: 'howrah-maidan', fare: 50 },
  { from: 'jai-hind', to: 'salt-lake-sector-v', fare: 70 },
  { from: 'jai-hind', to: 'hemanta-mukhopadhyay', fare: 65 },
  { from: 'jai-hind', to: 'beleghata', fare: 65 },
  
  // From Hemanta Mukhopadhyay (Ruby)
  { from: 'hemanta-mukhopadhyay', to: 'dakshineswar', fare: 45 },
  { from: 'hemanta-mukhopadhyay', to: 'dum-dum', fare: 45 },
  { from: 'hemanta-mukhopadhyay', to: 'girish-park', fare: 40 },
  { from: 'hemanta-mukhopadhyay', to: 'esplanade', fare: 40 },
  { from: 'hemanta-mukhopadhyay', to: 'park-street', fare: 40 },
  { from: 'hemanta-mukhopadhyay', to: 'mahanayak-uttam-kumar', fare: 35 },
  { from: 'hemanta-mukhopadhyay', to: 'howrah-maidan', fare: 50 },
  { from: 'hemanta-mukhopadhyay', to: 'sealdah', fare: 50 },

  // From Jessore Road
  { from: 'jessore-road', to: 'shyambazar', fare: 35 },
  { from: 'jessore-road', to: 'central', fare: 35 },
  { from: 'jessore-road', to: 'girish-park', fare: 35 },
  { from: 'jessore-road', to: 'chandni-chowk', fare: 40 },
  { from: 'jessore-road', to: 'esplanade', fare: 40 },
  { from: 'jessore-road', to: 'park-street', fare: 40 },
  { from: 'jessore-road', to: 'rabindra-sarobar', fare: 40 },
  { from: 'jessore-road', to: 'mahanayak-uttam-kumar', fare: 40 },
  { from: 'jessore-road', to: 'kavi-subhash', fare: 45 },
  { from: 'jessore-road', to: 'howrah-maidan', fare: 50 },
  { from: 'jessore-road', to: 'howrah', fare: 50 },
  { from: 'jessore-road', to: 'salt-lake-sector-v', fare: 70 },
  { from: 'jessore-road', to: 'hemanta-mukhopadhyay', fare: 65 },
  { from: 'jessore-road', to: 'beleghata', fare: 65 },
  
  // From Dum Dum Cantonment
  { from: 'dumdum-cantonment', to: 'shyambazar', fare: 25 },
  { from: 'dumdum-cantonment', to: 'central', fare: 25 },
  { from: 'dumdum-cantonment', to: 'girish-park', fare: 25 },
  { from: 'dumdum-cantonment', to: 'chandni-chowk', fare: 30 },
  { from: 'dumdum-cantonment', to: 'esplanade', fare: 30 },
  { from: 'dumdum-cantonment', to: 'park-street', fare: 30 },
  { from: 'dumdum-cantonment', to: 'rabindra-sarobar', fare: 30 },
  { from: 'dumdum-cantonment', to: 'mahanayak-uttam-kumar', fare: 30 },
  { from: 'dumdum-cantonment', to: 'kavi-subhash', fare: 35 },
  { from: 'dumdum-cantonment', to: 'howrah-maidan', fare: 40 },
  { from: 'dumdum-cantonment', to: 'howrah', fare: 40 },
  { from: 'dumdum-cantonment', to: 'sealdah', fare: 40 },
  { from: 'dumdum-cantonment', to: 'salt-lake-sector-v', fare: 60 },
  { from: 'dumdum-cantonment', to: 'hemanta-mukhopadhyay', fare: 55 },
  { from: 'dumdum-cantonment', to: 'beleghata', fare: 55 },

  // Blue Line to Green Line Fares
  { from: 'dakshineswar', to: 'sealdah', fare: 30 },
  { from: 'dakshineswar', to: 'phoolbagan', fare: 30 },
  { from: 'dakshineswar', to: 'bengal-chemical', fare: 40 },
  { from: 'dakshineswar', to: 'salt-lake-stadium', fare: 40 },
  { from: 'dakshineswar', to: 'salt-lake-sector-v', fare: 50 },
  { from: 'dakshineswar', to: 'central-park', fare: 40 },
  { from: 'dakshineswar', to: 'karunamoyee', fare: 50 },
  { from: 'dakshineswar', to: 'city-center', fare: 40 },
  { from: 'dakshineswar', to: 'howrah', fare: 30 },
  { from: 'dakshineswar', to: 'howrah-maidan', fare: 30 },
  { from: 'dakshineswar', to: 'mahakaran', fare: 25 },
  { from: 'dum-dum', to: 'sealdah', fare: 25 },
  { from: 'dum-dum', to: 'phoolbagan', fare: 25 },
  { from: 'dum-dum', to: 'bengal-chemical', fare: 35 },
  { from: 'dum-dum', to: 'salt-lake-stadium', fare: 35 },
  { from: 'dum-dum', to: 'salt-lake-sector-v', fare: 45 },
  { from: 'dum-dum', to: 'central-park', fare: 35 },
  { from: 'dum-dum', to: 'karunamoyee', fare: 45 },
  { from: 'dum-dum', to: 'city-center', fare: 35 },
  { from: 'dum-dum', to: 'howrah', fare: 25 },
  { from: 'dum-dum', to: 'howrah-maidan', fare: 25 },
  { from: 'dum-dum', to: 'mahakaran', fare: 20 },
  { from: 'belgachia', to: 'sealdah', fare: 25 },
  { from: 'belgachia', to: 'phoolbagan', fare: 25 },
  { from: 'belgachia', to: 'bengal-chemical', fare: 35 },
  { from: 'belgachia', to: 'salt-lake-stadium', fare: 35 },
  { from: 'belgachia', to: 'salt-lake-sector-v', fare: 45 },
  { from: 'belgachia', to: 'central-park', fare: 35 },
  { from: 'belgachia', to: 'karunamoyee', fare: 45 },
  { from: 'belgachia', to: 'city-center', fare: 35 },
  { from: 'belgachia', to: 'howrah', fare: 25 },
  { from: 'belgachia', to: 'howrah-maidan', fare: 25 },
  { from: 'belgachia', to: 'mahakaran', fare: 20 },
  { from: 'shyambazar', to: 'sealdah', fare: 25 },
  { from: 'shyambazar', to: 'phoolbagan', fare: 25 },
  { from: 'shyambazar', to: 'bengal-chemical', fare: 35 },
  { from: 'shyambazar', to: 'salt-lake-stadium', fare: 35 },
  { from: 'shyambazar', to: 'salt-lake-sector-v', fare: 45 },
  { from: 'shyambazar', to: 'central-park', fare: 35 },
  { from: 'shyambazar', to: 'karunamoyee', fare: 45 },
  { from: 'shyambazar', to: 'city-center', fare: 35 },
  { from: 'shyambazar', to: 'howrah', fare: 25 },
  { from: 'shyambazar', to: 'howrah-maidan', fare: 25 },
  { from: 'shyambazar', to: 'mahakaran', fare: 20 },
  { from: 'girish-park', to: 'sealdah', fare: 20 },
  { from: 'girish-park', to: 'phoolbagan', fare: 20 },
  { from: 'girish-park', to: 'bengal-chemical', fare: 30 },
  { from: 'girish-park', to: 'salt-lake-stadium', fare: 30 },
  { from: 'girish-park', to: 'salt-lake-sector-v', fare: 40 },
  { from: 'girish-park', to: 'central-park', fare: 30 },
  { from: 'girish-park', to: 'karunamoyee', fare: 40 },
  { from: 'girish-park', to: 'city-center', fare: 30 },
  { from: 'girish-park', to: 'howrah', fare: 20 },
  { from: 'girish-park', to: 'howrah-maidan', fare: 20 },
  { from: 'girish-park', to: 'mahakaran', fare: 15 },
  { from: 'mahatma-gandhi-road', to: 'sealdah', fare: 20 },
  { from: 'mahatma-gandhi-road', to: 'phoolbagan', fare: 20 },
  { from: 'mahatma-gandhi-road', to: 'bengal-chemical', fare: 30 },
  { from: 'mahatma-gandhi-road', to: 'salt-lake-stadium', fare: 30 },
  { from: 'mahatma-gandhi-road', to: 'salt-lake-sector-v', fare: 40 },
  { from: 'mahatma-gandhi-road', to: 'central-park', fare: 30 },
  { from: 'mahatma-gandhi-road', to: 'karunamoyee', fare: 40 },
  { from: 'mahatma-gandhi-road', to: 'city-center', fare: 30 },
  { from: 'mahatma-gandhi-road', to: 'howrah', fare: 20 },
  { from: 'mahatma-gandhi-road', to: 'howrah-maidan', fare: 20 },
  { from: 'mahatma-gandhi-road', to: 'mahakaran', fare: 15 },
  { from: 'central', to: 'sealdah', fare: 15 },
  { from: 'central', to: 'phoolbagan', fare: 15 },
  { from: 'central', to: 'bengal-chemical', fare: 25 },
  { from: 'central', to: 'salt-lake-stadium', fare: 25 },
  { from: 'central', to: 'salt-lake-sector-v', fare: 35 },
  { from: 'central', to: 'central-park', fare: 25 },
  { from: 'central', to: 'karunamoyee', fare: 35 },
  { from: 'central', to: 'city-center', fare: 25 },
  { from: 'central', to: 'howrah', fare: 15 },
  { from: 'central', to: 'howrah-maidan', fare: 15 },
  { from: 'central', to: 'mahakaran', fare: 10 },
  { from: 'chandni-chowk', to: 'sealdah', fare: 15 },
  { from: 'chandni-chowk', to: 'phoolbagan', fare: 15 },
  { from: 'chandni-chowk', to: 'bengal-chemical', fare: 25 },
  { from: 'chandni-chowk', to: 'salt-lake-stadium', fare: 25 },
  { from: 'chandni-chowk', to: 'salt-lake-sector-v', fare: 35 },
  { from: 'chandni-chowk', to: 'central-park', fare: 25 },
  { from: 'chandni-chowk', to: 'karunamoyee', fare: 35 },
  { from: 'chandni-chowk', to: 'city-center', fare: 25 },
  { from: 'chandni-chowk', to: 'howrah', fare: 15 },
  { from: 'chandni-chowk', to: 'howrah-maidan', fare: 15 },
  { from: 'chandni-chowk', to: 'mahakaran', fare: 10 },
  { from: 'park-street', to: 'sealdah', fare: 15 },
  { from: 'park-street', to: 'phoolbagan', fare: 15 },
  { from: 'park-street', to: 'bengal-chemical', fare: 25 },
  { from: 'park-street', to: 'salt-lake-stadium', fare: 25 },
  { from: 'park-street', to: 'salt-lake-sector-v', fare: 35 },
  { from: 'park-street', to: 'central-park', fare: 25 },
  { from: 'park-street', to: 'karunamoyee', fare: 35 },
  { from: 'park-street', to: 'city-center', fare: 25 },
  { from: 'park-street', to: 'howrah', fare: 15 },
  { from: 'park-street', to: 'howrah-maidan', fare: 15 },
  { from: 'park-street', to: 'mahakaran', fare: 10 },
  { from: 'maidan', to: 'sealdah', fare: 15 },
  { from: 'maidan', to: 'phoolbagan', fare: 15 },
  { from: 'maidan', to: 'bengal-chemical', fare: 25 },
  { from: 'maidan', to: 'salt-lake-stadium', fare: 25 },
  { from: 'maidan', to: 'salt-lake-sector-v', fare: 35 },
  { from: 'maidan', to: 'central-park', fare: 25 },
  { from: 'maidan', to: 'karunamoyee', fare: 35 },
  { from: 'maidan', to: 'city-center', fare: 25 },
  { from: 'maidan', to: 'howrah', fare: 15 },
  { from: 'maidan', to: 'howrah-maidan', fare: 15 },
  { from: 'maidan', to: 'mahakaran', fare: 10 },
  { from: 'rabindra-sadan', to: 'sealdah', fare: 20 },
  { from: 'rabindra-sadan', to: 'phoolbagan', fare: 20 },
  { from: 'rabindra-sadan', to: 'bengal-chemical', fare: 30 },
  { from: 'rabindra-sadan', to: 'salt-lake-stadium', fare: 30 },
  { from: 'rabindra-sadan', to: 'salt-lake-sector-v', fare: 40 },
  { from: 'rabindra-sadan', to: 'central-park', fare: 30 },
  { from: 'rabindra-sadan', to: 'karunamoyee', fare: 40 },
  { from: 'rabindra-sadan', to: 'city-center', fare: 30 },
  { from: 'rabindra-sadan', to: 'howrah', fare: 20 },
  { from: 'rabindra-sadan', to: 'howrah-maidan', fare: 20 },
  { from: 'rabindra-sadan', to: 'mahakaran', fare: 15 },
  { from: 'netaji-bhavan', to: 'sealdah', fare: 20 },
  { from: 'netaji-bhavan', to: 'phoolbagan', fare: 20 },
  { from: 'netaji-bhavan', to: 'bengal-chemical', fare: 30 },
  { from: 'netaji-bhavan', to: 'salt-lake-stadium', fare: 30 },
  { from: 'netaji-bhavan', to: 'salt-lake-sector-v', fare: 40 },
  { from: 'netaji-bhavan', to: 'central-park', fare: 30 },
  { from: 'netaji-bhavan', to: 'karunamoyee', fare: 40 },
  { from: 'netaji-bhavan', to: 'city-center', fare: 30 },
  { from: 'netaji-bhavan', to: 'howrah', fare: 20 },
  { from: 'netaji-bhavan', to: 'howrah-maidan', fare: 20 },
  { from: 'netaji-bhavan', to: 'mahakaran', fare: 15 },
  { from: 'jatindas-park', to: 'sealdah', fare: 20 },
  { from: 'jatindas-park', to: 'phoolbagan', fare: 20 },
  { from: 'jatindas-park', to: 'bengal-chemical', fare: 30 },
  { from: 'jatindas-park', to: 'salt-lake-stadium', fare: 30 },
  { from: 'jatindas-park', to: 'salt-lake-sector-v', fare: 40 },
  { from: 'jatindas-park', to: 'central-park', fare: 30 },
  { from: 'jatindas-park', to: 'karunamoyee', fare: 40 },
  { from: 'jatindas-park', to: 'city-center', fare: 30 },
  { from: 'jatindas-park', to: 'howrah', fare: 20 },
  { from: 'jatindas-park', to: 'howrah-maidan', fare: 20 },
  { from: 'jatindas-park', to: 'mahakaran', fare: 15 },
  { from: 'kalighat', to: 'sealdah', fare: 25 },
  { from: 'kalighat', to: 'phoolbagan', fare: 25 },
  { from: 'kalighat', to: 'bengal-chemical', fare: 35 },
  { from: 'kalighat', to: 'salt-lake-stadium', fare: 35 },
  { from: 'kalighat', to: 'salt-lake-sector-v', fare: 45 },
  { from: 'kalighat', to: 'central-park', fare: 35 },
  { from: 'kalighat', to: 'karunamoyee', fare: 45 },
  { from: 'kalighat', to: 'city-center', fare: 35 },
  { from: 'kalighat', to: 'howrah', fare: 25 },
  { from: 'kalighat', to: 'howrah-maidan', fare: 25 },
  { from: 'kalighat', to: 'mahakaran', fare: 20 },
  { from: 'rabindra-sarobar', to: 'sealdah', fare: 25 },
  { from: 'rabindra-sarobar', to: 'phoolbagan', fare: 25 },
  { from: 'rabindra-sarobar', to: 'bengal-chemical', fare: 35 },
  { from: 'rabindra-sarobar', to: 'salt-lake-stadium', fare: 35 },
  { from: 'rabindra-sarobar', to: 'salt-lake-sector-v', fare: 45 },
  { from: 'rabindra-sarobar', to: 'central-park', fare: 35 },
  { from: 'rabindra-sarobar', to: 'karunamoyee', fare: 45 },
  { from: 'rabindra-sarobar', to: 'city-center', fare: 35 },
  { from: 'rabindra-sarobar', to: 'howrah', fare: 25 },
  { from: 'rabindra-sarobar', to: 'howrah-maidan', fare: 25 },
  { from: 'rabindra-sarobar', to: 'mahakaran', fare: 20 },
  { from: 'mahanayak-uttam-kumar', to: 'sealdah', fare: 25 },
  { from: 'mahanayak-uttam-kumar', to: 'phoolbagan', fare: 25 },
  { from: 'mahanayak-uttam-kumar', to: 'bengal-chemical', fare: 35 },
  { from: 'mahanayak-uttam-kumar', to: 'salt-lake-stadium', fare: 35 },
  { from: 'mahanayak-uttam-kumar', to: 'salt-lake-sector-v', fare: 45 },
  { from: 'mahanayak-uttam-kumar', to: 'central-park', fare: 35 },
  { from: 'mahanayak-uttam-kumar', to: 'karunamoyee', fare: 45 },
  { from: 'mahanayak-uttam-kumar', to: 'city-center', fare: 35 },
  { from: 'mahanayak-uttam-kumar', to: 'howrah', fare: 25 },
  { from: 'mahanayak-uttam-kumar', to: 'howrah-maidan', fare: 25 },
  { from: 'mahanayak-uttam-kumar', to: 'mahakaran', fare: 20 },
  { from: 'netaji', to: 'sealdah', fare: 25 },
  { from: 'netaji', to: 'phoolbagan', fare: 25 },
  { from: 'netaji', to: 'bengal-chemical', fare: 35 },
  { from: 'netaji', to: 'salt-lake-stadium', fare: 35 },
  { from: 'netaji', to: 'salt-lake-sector-v', fare: 45 },
  { from: 'netaji', to: 'central-park', fare: 35 },
  { from: 'netaji', to: 'karunamoyee', fare: 45 },
  { from: 'netaji', to: 'city-center', fare: 35 },
  { from: 'netaji', to: 'howrah', fare: 25 },
  { from: 'netaji', to: 'howrah-maidan', fare: 25 },
  { from: 'netaji', to: 'mahakaran', fare: 20 },
  { from: 'masterda-surya-sen', to: 'sealdah', fare: 30 },
  { from: 'masterda-surya-sen', to: 'phoolbagan', fare: 30 },
  { from: 'masterda-surya-sen', to: 'bengal-chemical', fare: 40 },
  { from: 'masterda-surya-sen', to: 'salt-lake-stadium', fare: 40 },
  { from: 'masterda-surya-sen', to: 'salt-lake-sector-v', fare: 50 },
  { from: 'masterda-surya-sen', to: 'central-park', fare: 40 },
  { from: 'masterda-surya-sen', to: 'karunamoyee', fare: 50 },
  { from: 'masterda-surya-sen', to: 'city-center', fare: 40 },
  { from: 'masterda-surya-sen', to: 'howrah', fare: 30 },
  { from: 'masterda-surya-sen', to: 'howrah-maidan', fare: 30 },
  { from: 'masterda-surya-sen', to: 'mahakaran', fare: 25 },
  { from: 'gitanjali', to: 'sealdah', fare: 30 },
  { from: 'gitanjali', to: 'phoolbagan', fare: 30 },
  { from: 'gitanjali', to: 'bengal-chemical', fare: 40 },
  { from: 'gitanjali', to: 'salt-lake-stadium', fare: 40 },
  { from: 'gitanjali', to: 'salt-lake-sector-v', fare: 50 },
  { from: 'gitanjali', to: 'central-park', fare: 40 },
  { from: 'gitanjali', to: 'karunamoyee', fare: 50 },
  { from: 'gitanjali', to: 'city-center', fare: 40 },
  { from: 'gitanjali', to: 'howrah', fare: 30 },
  { from: 'gitanjali', to: 'howrah-maidan', fare: 30 },
  { from: 'gitanjali', to: 'mahakaran', fare: 25 },
  { from: 'kavi-nazrul', to: 'sealdah', fare: 30 },
  { from: 'kavi-nazrul', to: 'phoolbagan', fare: 30 },
  { from: 'kavi-nazrul', to: 'bengal-chemical', fare: 40 },
  { from: 'kavi-nazrul', to: 'salt-lake-stadium', fare: 40 },
  { from: 'kavi-nazrul', to: 'salt-lake-sector-v', fare: 50 },
  { from: 'kavi-nazrul', to: 'central-park', fare: 40 },
  { from: 'kavi-nazrul', to: 'karunamoyee', fare: 50 },
  { from: 'kavi-nazrul', to: 'city-center', fare: 40 },
  { from: 'kavi-nazrul', to: 'howrah', fare: 30 },
  { from: 'kavi-nazrul', to: 'howrah-maidan', fare: 30 },
  { from: 'kavi-nazrul', to: 'mahakaran', fare: 25 },
  { from: 'shahid-khudiram', to: 'sealdah', fare: 30 },
  { from: 'shahid-khudiram', to: 'phoolbagan', fare: 30 },
  { from: 'shahid-khudiram', to: 'bengal-chemical', fare: 40 },
  { from: 'shahid-khudiram', to: 'salt-lake-stadium', fare: 40 },
  { from: 'shahid-khudiram', to: 'salt-lake-sector-v', fare: 50 },
  { from: 'shahid-khudiram', to: 'central-park', fare: 40 },
  { from: 'shahid-khudiram', to: 'karunamoyee', fare: 50 },
  { from: 'shahid-khudiram', to: 'city-center', fare: 40 },
  { from: 'shahid-khudiram', to: 'howrah', fare: 30 },
  { from: 'shahid-khudiram', to: 'howrah-maidan', fare: 30 },
  { from: 'shahid-khudiram', to: 'mahakaran', fare: 25 },
  { from: 'kavi-subhash', to: 'sealdah', fare: 30 },
  { from: 'kavi-subhash', to: 'phoolbagan', fare: 30 },
  { from: 'kavi-subhash', to: 'bengal-chemical', fare: 40 },
  { from: 'kavi-subhash', to: 'salt-lake-stadium', fare: 40 },
  { from: 'kavi-subhash', to: 'salt-lake-sector-v', fare: 50 },
  { from: 'kavi-subhash', to: 'central-park', fare: 40 },
  { from: 'kavi-subhash', to: 'karunamoyee', fare: 50 },
  { from: 'kavi-subhash', to: 'city-center', fare: 40 },
  { from: 'kavi-subhash', to: 'howrah', fare: 30 },
  { from: 'kavi-subhash', to: 'howrah-maidan', fare: 30 },
  { from: 'kavi-subhash', to: 'mahakaran', fare: 25 },
  { from: 'shobhabazar-sutanuti', to: 'sealdah', fare: 20 },
  { from: 'shobhabazar-sutanuti', to: 'phoolbagan', fare: 20 },
  { from: 'shobhabazar-sutanuti', to: 'bengal-chemical', fare: 30 },
  { from: 'shobhabazar-sutanuti', to: 'salt-lake-stadium', fare: 30 },
  { from: 'shobhabazar-sutanuti', to: 'salt-lake-sector-v', fare: 40 },
  { from: 'shobhabazar-sutanuti', to: 'central-park', fare: 30 },
  { from: 'shobhabazar-sutanuti', to: 'karunamoyee', fare: 40 },
  { from: 'shobhabazar-sutanuti', to: 'city-center', fare: 30 },
  { from: 'shobhabazar-sutanuti', to: 'howrah', fare: 20 },
  { from: 'shobhabazar-sutanuti', to: 'howrah-maidan', fare: 20 },
  { from: 'shobhabazar-sutanuti', to: 'mahakaran', fare: 15 },
  { from: 'noapara', to: 'sealdah', fare: 30 },
  { from: 'noapara', to: 'phoolbagan', fare: 30 },
  { from: 'noapara', to: 'bengal-chemical', fare: 40 },
  { from: 'noapara', to: 'salt-lake-stadium', fare: 40 },
  { from: 'noapara', to: 'salt-lake-sector-v', fare: 50 },
  { from: 'noapara', to: 'central-park', fare: 40 },
  { from: 'noapara', to: 'karunamoyee', fare: 50 },
  { from: 'noapara', to: 'city-center', fare: 40 },
  { from: 'noapara', to: 'howrah', fare: 30 },
  { from: 'noapara', to: 'howrah-maidan', fare: 30 },
  { from: 'noapara', to: 'mahakaran', fare: 25 },
  { from: 'baranagar', to: 'sealdah', fare: 30 },
  { from: 'baranagar', to: 'phoolbagan', fare: 30 },
  { from: 'baranagar', to: 'bengal-chemical', fare: 40 },
  { from: 'baranagar', to: 'salt-lake-stadium', fare: 40 },
  { from: 'baranagar', to: 'salt-lake-sector-v', fare: 50 },
  { from: 'baranagar', to: 'central-park', fare: 40 },
  { from: 'baranagar', to: 'karunamoyee', fare: 50 },
  { from: 'baranagar', to: 'city-center', fare: 40 },
  { from: 'baranagar', to: 'howrah', fare: 30 },
  { from: 'baranagar', to: 'howrah-maidan', fare: 30 },
  { from: 'baranagar', to: 'mahakaran', fare: 25 }
];

    

    






